Development
DanielMitiku/Embedding-images-and-videos pull request #1
Opened 2019-02-25 15:51 UTC by DanielMitiku

2019-02-25 19:42 UTC, inhaq requested changes
### Great work on your first project 🏆
Kindly look into these changes mentioned below. Also It doesn't look fine with me in chrome, check screenshot [here](https://snag.gy/wisSJ2.jpg). 
I would also recommend to add `img` folder and put all images in it and update links accordingly.
In order to see whether your HTML is good, you can validate it [here](https://validator.w3.org). Once you finished with the project, kindly resubmit it and mentioned me(Inzimam) in reviewed before. Happy coding!

2019-02-25 19:42 UTC, inhaq commented on index.html
> +<!DOCTYPE html>
Good work on adding a `doctype` 😊

2019-02-25 19:42 UTC, inhaq commented on index.html
> +<html>
Add a `lang` attribute to the `html` tag to declare the language of this document.

2019-02-25 19:42 UTC, inhaq commented on index.html
> +		<li><a href="#"><img  src="menu.PNG"></a></li>
An `img` element must have an `alt` attribute that is to be rendered when the element to which it is applied cannot be rendered.

2019-02-25 19:42 UTC, inhaq commented on index.html
> +		<li id="search"><input id="input" type="text" placeholder="Search" width="400px" margin-right="40px"><button id="search-button"><img id="button" src="search.PNG" ></button></li></a></li>
Attribute `width` and `margin-right` not allowed on element `input`.
No opening tag for `a` exists also `li` tag is closed twice.

2019-02-25 19:42 UTC, inhaq commented on index.html
> +		<iframe width="600" height="400" src="https://www.youtube.com/embed/NnO08HnZf10" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></if
The `frameborder` attribute on the `iframe` element is obsolete.

2019-02-26 12:47 UTC, inhaq requested changes
Good work on applying all these suggestions but you need to make the design look bit better. Let me [share the screenshot](https://snag.gy/XHkcl3.jpg). Kindly look into it and update your code. Once you're done, kindly resubmit the project.

2019-02-26 12:47 UTC, inhaq commented on index.html
> +		<li><a href="#"><img  src="img/menu.PNG" alt="Missing Img"></a></li>
`alt` tag should have text related to the image. For example, if it's a cat image than `alt` should be a cat. It should contain information about that image.

2019-02-26 15:32 UTC, DanielMitiku commented
Hey, It looks fine in our browser.

2019-02-26 15:37 UTC, DanielMitiku commented
![capture](https://user-images.githubusercontent.com/32415787/53425104-7f7a4100-39f5-11e9-8ee9-8c776d7a7ba1.JPG)

2019-02-26 15:48 UTC, inhaq commented
> Hey, It looks fine in our browser.
I can see it looks fine on 720 resolution screens but try to zoom out and you'll see the problem on your screen as well. Also, one more thing, check inspector tools in chrome and see your body is broken. Let me know if you need more info.

2019-02-26 15:57 UTC, DanielMitiku commented
So what do we do! This is our first assignment and it doesn't talk about screen sizes. May be you can help us!

2019-02-26 19:03 UTC, inhaq commented
[This](https://www.codeproject.com/Articles/762201/Adjusting-your-websites-to-fit-all-types-of-resolu) might help you, the goal of this project is not to make it responsive for every screen but at least it should work on a few laptop resolutions. If you guys need help, don't hesitate to ask or you can go to your dashboard and click on technical support to help with technical problems.

2019-02-27 06:10 UTC, DanielMitiku commented
Did you see the screenshot? It works on our laptop!

2019-02-27 08:33 UTC, inhaq commented
> Did you see the screenshot? It works on our laptop!

I can see it like [this](https://snag.gy/cnSyz3.jpg).
1. Doesn't look right, as I mentioned in this screenshot as point 1.
2. Why is this line popping up on screen?
You guys did an awesome work as a first project but I want you to make it as good as possible. If you're happy with what you've done, kindly make these two changes and submit it. I'll 👍🏻. But I'm here to help you guys deliver excellent projects which look good on your CV. Hope you understand. In case of technical questions, you can reach to technical support in your dashboard.

2019-02-27 08:48 UTC, DanielMitiku commented
Hey inhaq, I've edited it. Please take a look at it.

2019-02-27 08:59 UTC, inhaq commented
> Hey inhaq, I've edited it. Please take a look at it.

I just looked into it. [This](https://snag.gy/BXouvY.jpg) needs some styling. Specifically, views, share, likes should be aligned with the title. 
Take your time with this project, the more time you make this one awesome, the lesser time you'll spend on new projects. If you rushed this one, then you guys will get more problems in next HTML/CSS projects as well. I want you to go through more readings and guides to understand this part of program very well. I'm sure you guys will do the best possible work very soon.

2019-02-27 09:17 UTC, DanielMitiku commented
Can you look at it now!

2019-02-27 09:29 UTC, inhaq commented
I really think you did a great job for your screen size, but as the project states, this should be responsive to more than just 1 screen size. If you were to put this project in your portfolio right now, and a potential employer was to look at it with different screen size, they wouldn't think you did a very good job. All of the projects you make now will be part of your final portfolio and are supposed to help you get a job. This one won't do that unless the employer happens to have the exact same screen size as you. I'd recommend you reading here, here and here to brush up on responsive design(at least for laptop resolutions, no need for media queries) to make sure your project will be good to get the thumbs up.

2019-02-27 13:27 UTC, DanielMitiku commented
The here, here and here are not links

2019-02-27 13:27 UTC, DanielMitiku commented
Did you look at it

2019-02-27 19:24 UTC, inhaq commented
### 👍🏻 for this project 🥇
Congrats on completing this project. I know you guys have tried way hard and in the mean time also learn lots of things. But one thing which I wanted to say to keep in mind to have more effort in next project. This one is the first one and I know you guys will do next one way better. Go ahead and submit the project completion form. Happy coding 🎉

2019-02-27 19:37 UTC, inhaq approved these changes
### 👍🏻 for this project 🥇
Congrats on completing this project. I know you guys have tried way hard and in the mean time also learn lots of things. But one thing which I wanted to say to keep in mind to have more effort in next project. This one is the first one and I know you guys will do next one way better. Go ahead and submit the project completion form. Happy coding 🎉

2019-03-01 05:47 UTC, merged